spring:
  application:
    name: StoreCalcio
  datasource:
    username: "root"
    password: "database"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/progettostoredb
    jpa:
      database-platform: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/Store
    

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8081

jwt:
  auth:
    converter:
      resource-id: StoreClient
      principal-attribute: preferred_username